/* tslint:disable */
/* eslint-disable */
/**
 * Zingle API (Current)
 * Zingle Core API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@zingleme.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

